### ISSUE TITLE
[Q] How to do provisioning?

### ISSUE THREAD

**Issue by kgroshert** [bmcsoftware/bmchelix-datasource#6]
Hello, after installing the plugin, can you provide some info how to configure the plugin using grafana-provisioning?
I could not find it in the documentation and of course I don't want to setup the plugin manually.

Thanks!

**Comment by kgroshert** [comment]
To answer my own question, could you verify that this is correct and maybe put it in the README?

```
datasources:
  - name: bmchelix-prod
    type: bmchelix-ade-datasource
    url: https://url.to.bmchelix/
    jsonData:
      tenantId: 123456789
    secureJsonData:
      accessKey: xxxxx
      secretKey: xxxxx
    readOnly: true
```

**Comment by bfarrell** [comment]
@kgroshert Thanks for digging in.  That looks correct.  We will do one validation on Monday and update the docs.

**Comment by abhijeet-teli** [comment]
Hi @kgroshert ,

We've validated the provisioning and it works fine you probably need to add few more attributes if you are using multiple orgs  
Here is the sample - 

```
datasources:
 - name: BMC Helix
   type: bmchelix-ade-datasource
   access: proxy
   orgId: 1
   url: https://abc.helix.bmc.com
   jsonData:
     tenantId: "123456789"
   secureJsonData:
    accessKey: "xxxxxx"
    secretKey: "xxxxxx"

#   <bool> mark as default datasource. Max one per org
#   isDefault: false
    
#   <bool> allow users to edit datasources from the UI.
#   editable: false

```
last two attributes are optional you can choose to leave them commented.

We will be releasing new version very soon, Will update the Readme for provisioning.

Thanks for pointing this out,

Let us know if you need any further details.
